server:
  port: ${PORT:8080}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

management:
  security:
    enabled: false

logging:
  level:
    cloud.aluno.DisciplinaClient: DEBUG      
   
feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true    
    
---
spring:
  profiles: ribbon-only
  jpa:
    show-sql: true

server:
  port: ${PORT:8080}

disciplina-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8081,localhost:18081,localhost:28081
    ServerListRefreshInterval: 15000