server:
  port: 8888

management:
  security:
    enabled: false

spring:
  cloud:
    bus:
      enabled: true
    config:
      server:
        git:
          uri: file:///Users/rodrigo/Desktop/config-repo          
  rabbitmq:
    host: localhost
    port: 5672    
    
security:
  user:
    name: configUser
    password: configPassword
    role: SYSTEM